### ISSUE TITLE
Question on use of engine.iterate()

### ISSUE THREAD

**Issue by matatk** [parente/pyttsx#11]
I am trying to use pyttsx to speak everything that comes out of the stdout of a process (currently on Mac, but on Windows too in future).  Because I have to loop over the stdout of the process, I am trying to use pyttsx with my own event loop.  I believe I have followed the [example given in the docs](http://pyttsx.readthedocs.org/en/v1.1/engine.html#examples), but the speech output stalls after the first message.  I have added some print statements to the pyttsx code and found that the `engine.iterate()` call does not appear to reach the driver I am using (Mac).

I have put the TTS controller in a class and wrapped it so that the class can be used from a with statement, in order to ensure cleanup occurs.

``` python
class SpeakerManager(object):
    """Provide a context to for using Speaker in with statements."""
    def __enter__(self):    
        class Speaker(object):
            """Performs Text-To-Speech"""
            def __init__(self):
                self._engine = pyttsx.init()
                self._engine.startLoop(False)

            def say(self, message):
                sys.stdout.write("say: " + message)
                self._engine.say(message)
                self._engine.iterate()

            def cleanup(self):
                self._engine.endLoop()

        self.speaker = Speaker()
        return self.speaker

    def __exit__(self, type, value, traceback):
        self.speaker.cleanup()
```

This is how I am using the TTS, to speak everything that comes from the stdout of a process:

``` python
def launch(command_line):
    proc = subprocess.Popen(command_line, stdout=subprocess.PIPE)
    with SpeakerManager() as speaker:
        while True:
            retcode = proc.poll()
            line = proc.stdout.readline()
            speaker.say(line)
            if retcode is not None:
                break
```

I only get the first message spoken, but I get all of them printed out, prefixed with "say: " as per the code above.

I noted from the documentation something about the event loop needing manual management, but it seems that `engine.iterate()` is the cross-platform way to do this.  Wondering what I'm doing wrong :-).

Thanks for writing this library; simple cross-platform TTS is just what I am looking for!

**Comment by matatk** [comment]
Once again, many thanks for your time and help.  Here is the actual [finished and working](https://github.com/matatk/agrip/blob/master/audioquake/app-skel/Contents/MacOS/AudioQuake.py) code! :-)

**Update (2017):** that link no longer works as the file moved and has changed a lot since. I was asked for a working version of the link, so thought I'd put it here too (in case it's of any use to anyone in future). Here's [that file at the time it was fixed](https://github.com/matatk/agrip/blob/96fba93c354bc59a822f53cac0801b9e5c8f9ca4/audioquake/app-skel/Contents/MacOS/AudioQuake.py) (that's a helpful lesson: permalinks are good :-)).

**Comment by opalm** [comment]
It seems a problem solved long time ago.
Recently I got the same problem on OS X, and I found there might a solution by modify the nsss.py below:
-------
    def iterate(self):
        while True:  # there should be a loop for the it
            self._proxy.setBusy(False)
            yield
-------
