### ISSUE TITLE
Segfault on Ubuntu 10.10, 11.04

### ISSUE THREAD

**Issue by mrmekon** [parente/pyttsx#3]
<b>Situation:</b>

> > > import pyttsx
> > > pyttsx.init()
> > > Segmentation fault

<b>Cause:</b>
In pyttsx/drivers/espeak.py, in **init**(), self.getProperty('voice') results in a call to GetCurrentVoice() in _espeak.py, which calls espeak_GetCurrentVoice() in libespeak.so.1.  libespeak is returning a valid result with an empty name.  EspeakDriver._defaultVoice gets set to None.  A subsequent call to self.setProperty() references the None value, and causes a segmentation fault.

<b>Possible solution:</b>
I know nothing of espeak or its API.  Mine works, but does not return a 'current voice'.  This solved the problem on my machine:

Replace line 37 of espeak.py:

``` python
EspeakDriver._defaultVoice = self.getProperty('voice')
```

With this block:

``` python
EspeakDriver._defaultVoice = self.getProperty('voice')
if EspeakDriver._defaultVoice == None:
    EspeakDriver._defaultVoice = "en"
```

This just defaults to english if espeak doesn't return a voice.  Text-to-speech works as expected after this modification.

<b>Version information:</b>
Ubuntu Server 10.10
Python 2.7
pyttsx-1.0
libespeak1 version 1.44.05~really-1.44.04-0ubuntu1

**Comment by Marcogb81** [comment]
Hi!
I try use a module Chatterbot mixed with Pyttsx for do it speak the chaterbot, but the loop While cut de pronunciation of word chains, example: chatbot write: hello, computer only say "he". The example block code is:

`# chatbot empiieza
while True:
    speak = raw_input('- ')
    response = chatbot.get_response(speak)
    # dice la respuesta
    print response
    engine.say(response)
    # mantiene el TTS enn marcha
    engine.runAndWait()
`
